import 'package:wander_wise/attraction_cards/attractions.dart';

List<Attractions> attractions = [
  Attractions(
    name: 'Eiffel Tower',
    price: '\$',
    rating: '4.8',
    imagePath: 'asset/img/eiffel_tower.png',
    description: 'The Eiffel Tower, an iconic symbol of France, stands tall in the heart of Paris. Completed in 1889, this wrought-iron lattice tower offers breathtaking views of the city from its observation decks. Visitors can take an elevator ride or climb the stairs to witness the stunning panorama.',
    averagePrice: 'Adults: €16 - €26\nYouth (12-24 years): €8 - €13\nChildren (4-11 years): €4 - €10',
  ),
  Attractions(
    name: 'Mont Saint-Michel',
    price: '\$\$\$',
    rating: '4.6',
    imagePath: 'asset/img/mont_saint_michel.png',
    description: 'Mont Saint-Michel is a stunning island commune in Normandy, famous for its medieval abbey and picturesque setting. Surrounded by tidal waters, this UNESCO World Heritage site offers a unique blend of history, architecture, and natural beauty. Explore its narrow streets, ancient buildings, and the abbey itself.',
    averagePrice: 'Adults: €11\nReduced rate (18-25 years, non-EU): €8\nFree for EU residents under 26 and children under 18',
  ),
  Attractions(
    name: 'Arc de Triomphe',
    price: '\$',
    rating: '4.7',
    imagePath: 'asset/img/arc_de_triomphe.png',
    description: 'The Arc de Triomphe, located at the western end of the Champs-Élysées, is a monumental arch honoring those who fought and died for France during the French Revolutionary and Napoleonic Wars. Visitors can climb to the top for a spectacular view of Paris and its famous avenues converging at the Place Charles de Gaulle.',
    averagePrice: 'Adults: €13\nReduced rate: €11\nFree for EU residents under 26 and children under 18',
  ),
  Attractions(
    name: 'Etretat',
    price: '\$\$',
    rating: '4.8',
    imagePath: 'asset/img/etretat.png',
    description: 'Etretat is a charming coastal town in Normandy, renowned for its dramatic white cliffs and natural rock formations, including the famous Arch and Needle. The breathtaking landscape has inspired many artists, including Claude Monet. Visitors can enjoy scenic walks, beach activities, and the serene beauty of this unique destination.',
    averagePrice: 'Access to the cliffs and beach is free.\nVisits to gardens and local museums range from €6 to €12',
  ),
  Attractions(
    name: 'Louvre Museum',
    price: '\$\$',
    rating: '4.9',
    imagePath: 'asset/img/louvre_museum.png',
    description: 'The Louvre Museum in Paris, one of the world’s largest and most visited art museums, is home to thousands of works of art, including the Mona Lisa and the Venus de Milo. The museum offers an extensive collection spanning from ancient civilizations to the 19th century.',
    averagePrice: 'Adults: €15\nReduced rate (18-25 years, non-EU): €9\nFree for EU residents under 26 and children under 18',
  ),
  Attractions(
    name: 'Palace of Versailles',
    price: '\$\$\$',
    rating: '4.7',
    imagePath: 'asset/img/palace_of_versailles.png',
    description: 'The Palace of Versailles, a former royal residence located in Versailles, is known for its opulent architecture and expansive gardens. Visitors can explore the Hall of Mirrors, the Royal Apartments, and the meticulously manicured gardens.',
    averagePrice: 'Adults: €18\nReduced rate: €13\nFree for EU residents under 26 and children under 18',
  ),
  Attractions(
    name: 'Château de Chambord',
    price: '\$\$\$',
    rating: '4.5',
    imagePath: 'asset/img/chateau_de_chambord.png',
    description: 'The Château de Chambord, a stunning Renaissance castle located in the Loire Valley, is known for its distinctive French architecture and extensive grounds. The castle offers a glimpse into the grandeur of French royal history.',
    averagePrice: 'Adults: €14.50\nReduced rate (18-25 years, non-EU): €11\nFree for EU residents under 26 and children under 18',
  ),
  Attractions(
    name: 'Notre-Dame Cathedral',
    price: 'Free',
    rating: '4.8',
    imagePath: 'asset/img/notre_dame_cathedral.png',
    description: 'The Notre-Dame Cathedral, a masterpiece of French Gothic architecture, is located on the Île de la Cité in Paris. The cathedral is renowned for its stunning stained glass windows, flying buttresses, and the iconic twin towers.',
    averagePrice: 'Free entry\nTours: €10 - €20',
  ),
  Attractions(
    name: 'Père Lachaise Cemetery',
    price: 'Free',
    rating: '4.6',
    imagePath: 'asset/img/pere_lachaise_cemetery.png',
    description: 'Père Lachaise Cemetery in Paris is the final resting place of many famous figures, including Oscar Wilde, Jim Morrison, and Edith Piaf. The cemetery offers a peaceful and reflective environment with impressive funerary art and sculptures.',
    averagePrice: 'Free entry\nGuided tours: €10 - €15',
  ),
  Attractions(
    name: 'Pont du Gard',
    price: '\$\$',
    rating: '4.7',
    imagePath: 'asset/img/pont_du_gard.png',
    description: 'The Pont du Gard, an ancient Roman aqueduct bridge located in the South of France, is a marvel of engineering and historical significance. Visitors can explore the structure, visit the museum, and enjoy scenic walks along the river.',
    averagePrice: 'Adults: €9.50\nReduced rate: €7.50\nFree for children under 18',
  ),
  Attractions(
    name: 'Dune of Pilat',
    price: 'Free',
    rating: '4.9',
    imagePath: 'asset/img/dune_of_pilat.png',
    description: 'The Dune of Pilat, the tallest sand dune in Europe, is located on the Atlantic coast of France. The dune offers stunning views of the surrounding pine forests, the Atlantic Ocean, and the Banc d\'Arguin. It is a popular destination for hiking and paragliding.',
    averagePrice: 'Free entry\nParking: €6 - €10',
  ),
  Attractions(
    name: 'Cité de Carcassonne',
    price: '\$\$',
    rating: '4.7',
    imagePath: 'asset/img/cite_de_carcassonne.png',
    description: 'The Cité de Carcassonne, a medieval fortified city in the Languedoc region, is known for its double-walled ramparts and fairy-tale towers. The city offers a journey back in time with its cobbled streets, historical buildings, and the impressive Château Comtal.',
    averagePrice: 'Adults: €9.50\nReduced rate: €7.50\nFree for children under 18',
  ),
];
