final Map<String, Map<String, Map<String, String>>> baggageAllowance = {
  'American Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Delta Air Lines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'United Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Southwest Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (23kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Alaska Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'JetBlue Airways': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Spirit Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (18kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Frontier Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Allegiant Air': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (18kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Singapore Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (30kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (40kg total)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Cathay Pacific': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Japan Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'All Nippon Airways': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Korean Air': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Asiana Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'China Eastern Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'China Southern Airlines': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (23kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (32kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Air India': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (25kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (35kg each)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
  'Thai Airways': {
    'Economy': {
      'Allowance': '1 carry-on bag, 1 personal item, 1 checked bag (30kg)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
    'Business': {
      'Allowance': '1 carry-on bag, 1 personal item, 2 checked bags (40kg total)',
      'Liquids': 'Allowed in containers of 100ml or less, must fit in a quart-sized bag',
      'Sharp Objects': 'Not allowed in carry-on, allowed in checked baggage',
      'Electronics': 'Laptops and other large electronics must be removed from carry-on and screened separately',
      'Prohibited Items': 'Firearms, explosives, flammable liquids, etc.',
      'Special Items': 'Sports equipment and musical instruments allowed with special handling',
    },
  },
};
