// city_names.dart
const Map<String, String> cityNames = {
  'SEL': 'Seoul (SEL)',
  'TYO': 'Tokyo (TYO)',
  'KUL': 'Kuala Lumpur (KUL)',
  'TPE': 'Taipei (TPE)',
  'HKG': 'Hong Kong (HKG)',
  'DPS': 'Denpasar (DPS)',
  'MNL': 'Manila (MNL)',
  'LON': 'London (LON)',
  'PEN': 'Penang (PEN)',
  'IST': 'Istanbul (IST)',
  'DXB': 'Dubai (DXB)',
  'SHA': 'Shanghai (SHA)',
  'CAN': 'Guangzhou (CAN)',
  'BJS': 'Beijing (BJS)',
  'HGH': 'Hangzhou (HGH)',
  'OSA': 'Osaka (OSA)',
  'NGO': 'Nagoya (NGO)',
  'PUS': 'Busan (PUS)',
  'LAX': 'Los Angeles (LAX)',
  'CHI': 'Chicago (CHI)',
  'YTO': 'Toronto (YTO)',
  'YEA': 'Edmonton (YEA)',
  'VIE': 'Vienna (VIE)',
  'PAR': 'Paris (PAR)',
  'DUB': 'Dublin (DUB)',
  'LIS': 'Lisbon (LIS)',
  'GVA': 'Geneva (GVA)',
  'EDI': 'Edinburgh (EDI)',
  'BCN': 'Barcelona (BCN)',
  'DFW': 'Dallas/Fort Worth (DFW)',
  'DEN': 'Denver (DEN)',
  'DEL': 'Delhi (DEL)',
  'FRA': 'Frankfurt (FRA)',
  'BOM': 'Mumbai (BOM)',
  'BOS': 'Boston (BOS)',
  'AMS': 'Amsterdam (AMS)',
  'SYD': 'Sydney (SYD)',
  'MUC': 'Munich (MUC)',
  'MIA': 'Miami (MIA)',
  'MEX': 'Mexico City (MEX)',
  'SFO': 'San Francisco (SFO)',
  'YVR': 'Vancouver (YVR)',
  'LAS': 'Las Vegas (LAS)',
  'HNL': 'Honolulu (HNL)',
  'SCL': 'Santiago (SCL)',
  'LIM': 'Lima (LIM)',
  'BOG': 'Bogota (BOG)',
  'MAD': 'Madrid (MAD)',
  'ATH': 'Athens (ATH)',
  'BER': 'Berlin (BER)',
  'CPH': 'Copenhagen (CPH)',
  'PRG': 'Prague (PRG)',
  'WAW': 'Warsaw (WAW)',
  'ZRH': 'Zurich (ZRH)',
  'BKK': 'Bangkok (BKK)',
  'SGN': 'Ho Chi Minh City (SGN)',
  'KTM': 'Kathmandu (KTM)',
  'HKT': 'Phuket (HKT)',
  'HAN': 'Hanoi (HAN)',
  'CPT': 'Cape Town (CPT)',
  'JNB': 'Johannesburg (JNB)',
  'RAK': 'Marrakesh (RAK)',
  'NBO': 'Nairobi (NBO)',
  'CAI': 'Cairo (CAI)',
  'AKL': 'Auckland (AKL)',
  'MEL': 'Melbourne (MEL)',
  'BNE': 'Brisbane (BNE)',
  'TLV': 'Tel Aviv (TLV)',
  'DOH': 'Doha (DOH)',
  'AUH': 'Abu Dhabi (AUH)',
  'SIN': 'Singapore (SIN)'
};
