import 'package:wander_wise/food_cards/foods.dart';

List<Food> foods = [
  Food(
    name: 'Coq au Vin',
    price: '\$\$',
    rating: '4.8',
    imagePath: 'asset/img/coq_au_vin.png',
    description: 'Coq au Vin is a classic French dish that features chicken braised with red wine, mushrooms, onions, and bacon. This rich and hearty dish is a staple of French cuisine, offering a taste of rustic, slow-cooked flavors.',
    averagePrice: '€18 - €30',
  ),
  Food(
    name: 'Croissant',
    price: '\$',
    rating: '4.8',
    imagePath: 'asset/img/croissant.png',
    description: 'The croissant is a buttery, flaky, and golden pastry that is quintessentially French. Perfect for breakfast or a snack, it is enjoyed plain or filled with chocolate, almond paste, or ham and cheese.',
    averagePrice: '€2 - €4',
  ),
  Food(
    name: 'Boeuf Bourguignon',
    price: '\$\$\$',
    rating: '4.9',
    imagePath: 'asset/img/boeuf_bourguignon.png',
    description: 'Boeuf Bourguignon is a traditional French stew made with beef braised in red wine, often with carrots, onions, and garlic, and flavored with a bouquet garni. It is a hallmark of French culinary tradition, renowned for its deep, rich flavors.',
    averagePrice: '€20 - €35',
  ),
  Food(
    name: 'Ratatouille',
    price: '\$',
    rating: '4.7',
    imagePath: 'asset/img/ratatouille.png',
    description: 'Ratatouille is a colorful vegetable dish from the Provence region, typically made with tomatoes, zucchini, eggplant, bell peppers, onions, and seasoned with herbs. This healthy and flavorful dish can be served as a main or a side.',
    averagePrice: '€12 - €20',
  ),
  Food(
    name: 'Crème Brûlée',
    price: '\$\$',
    rating: '4.9',
    imagePath: 'asset/img/creme_brulee.png',
    description: 'Crème Brûlée is a creamy custard dessert topped with a contrasting layer of hard caramel. This elegant dessert, often flavored with vanilla, is a favorite in French cuisine for its delicate texture and delightful flavor.',
    averagePrice: '€6 - €12',
  ),
  Food(
    name: 'Bouillabaisse',
    price: '\$\$\$',
    rating: '4.6',
    imagePath: 'asset/img/bouillabaisse.png',
    description: 'Bouillabaisse is a traditional Provençal fish stew originating from the port city of Marseille. Made with various kinds of fish, shellfish, and vegetables, it is seasoned with herbs and saffron, and often served with rouille sauce and crusty bread.',
    averagePrice: '€25 - €40',
  ),
  Food(
    name: 'Macarons',
    price: '\$',
    rating: '4.8',
    imagePath: 'asset/img/macarons.png',
    description: 'Macarons are delicate French meringue-based cookies filled with ganache, buttercream, or jam. They come in a variety of flavors and colors, making them a popular and visually appealing treat.',
    averagePrice: '€1.50 - €3 each',
  ),
  Food(
    name: 'Tarte Tatin',
    price: '\$\$',
    rating: '4.7',
    imagePath: 'asset/img/tarte_tatin.png',
    description: 'Tarte Tatin is an upside-down caramelized apple tart. This rustic and indulgent dessert is known for its sweet, sticky, and buttery flavors, perfectly balancing the crisp pastry and soft apples.',
    averagePrice: '€6 - €12',
  ),
  Food(
    name: 'Escargots de Bourgogne',
    price: '\$\$',
    rating: '4.5',
    imagePath: 'asset/img/escargots_de_bourgogne.png',
    description: 'Escargots de Bourgogne are Burgundy snails cooked with garlic, parsley, and butter. This classic French appetizer is prized for its rich and garlicky flavor, typically served as a delicacy in many French restaurants.',
    averagePrice: '€15 - €25',
  ),
  Food(
    name: 'Quiche Lorraine',
    price: '\$',
    rating: '4.6',
    imagePath: 'asset/img/quiche_lorraine.png',
    description: 'Quiche Lorraine is a savory tart from the Lorraine region, made with a rich custard filling of eggs, cream, and bacon in a flaky pastry crust. This versatile dish is perfect for any meal and can be enjoyed hot or cold.',
    averagePrice: '€8 - €15',
  ),
];
