// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwb1CNTzSd79jO0vizb-1UZR_OSMml-K0',
    appId: '1:785844388160:web:9b1604b4ca7d24a68b7aa5',
    messagingSenderId: '785844388160',
    projectId: 'wanderwise-18703',
    authDomain: 'wanderwise-18703.firebaseapp.com',
    storageBucket: 'wanderwise-18703.appspot.com',
    measurementId: 'G-X61E4DYLJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlEDF4unRoVa4Flj8DK_HT3lYiYO1adU',
    appId: '1:785844388160:android:6d327035d4f9ee638b7aa5',
    messagingSenderId: '785844388160',
    projectId: 'wanderwise-18703',
    storageBucket: 'wanderwise-18703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrtS427TbHrHD4cXzzq9r0ezsQro4Ug1E',
    appId: '1:785844388160:ios:6a4572a44dc58ac18b7aa5',
    messagingSenderId: '785844388160',
    projectId: 'wanderwise-18703',
    storageBucket: 'wanderwise-18703.appspot.com',
    iosBundleId: 'com.example.wanderWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrtS427TbHrHD4cXzzq9r0ezsQro4Ug1E',
    appId: '1:785844388160:ios:6a4572a44dc58ac18b7aa5',
    messagingSenderId: '785844388160',
    projectId: 'wanderwise-18703',
    storageBucket: 'wanderwise-18703.appspot.com',
    iosBundleId: 'com.example.wanderWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwb1CNTzSd79jO0vizb-1UZR_OSMml-K0',
    appId: '1:785844388160:web:7183291f957e51c18b7aa5',
    messagingSenderId: '785844388160',
    projectId: 'wanderwise-18703',
    authDomain: 'wanderwise-18703.firebaseapp.com',
    storageBucket: 'wanderwise-18703.appspot.com',
    measurementId: 'G-51M16HXMSF',
  );
}
